name: radarr-tmc
services:
  app:
    cpu_shares: 50
    command: []
    container_name: radarr
    deploy:
      resources:
        limits:
          memory: 10166M
    image: lscr.io/linuxserver/radarr:develop
    labels:
      icon: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/icon.png
    ports:
      - target: 7878
        published: "40199"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/TMC-Store/radarr-tmc/config
        target: /config
      - type: bind
        source: /media/devmon/1TB EXT/downloads/movies
        target: /media
      - type: bind
        source: /media/devmon/1TB EXT/downloads/movies
        target: /movies
      - type: bind
        source: /media/devmon/1TB EXT
        target: /hdd
      - type: bind
        target: /6tb
        source: /6tb
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: radarr
  category: TMCstore
  description:
    en_us: Radarr is a movie collection manager for Usenet and BitTorrent users. It
      can monitor multiple RSS feeds for new movies and will interface with
      clients and indexers to grab, sort, and rename them. It can also be
      configured to automatically upgrade the quality of existing files in the
      library when a better quality format becomes available.
  developer: radarr
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/icon.png
  index: /
  main: app
  port_map: "40199"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/screenshot-01.png
    - https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/screenshot-02.png
    - https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/screenshot-03.png
    - https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/screenshot-04.png
  store_app_id: radarr-tmc
  tagline:
    en_us: Radarr is a movie collection manager for Usenet and BitTorrent users.
  thumbnail: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/radarr/thumbnail.png
  title:
    custom: ""
    en_us: Radarr v4+
